# Generated by Django 3.0.9 on 2020-08-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300)),
                ('PhoneNo', models.BooleanField(default=False)),
                ('Email', models.EmailField(max_length=25)),
                ('Address', models.CharField(max_length=220)),
                ('Password', models.CharField(max_length=100)),
                ('CPassword', models.CharField(max_length=100)),
            ],
        ),
    ]
