# Generated by Django 3.0.9 on 2020-08-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='PhoneNo',
            field=models.IntegerField(max_length=13),
        ),
    ]
