# Generated by Django 3.0.9 on 2020-08-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_auto_20200818_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='PhoneNo',
            field=models.IntegerField(),
        ),
    ]
