# Generated by Django 3.0.9 on 2020-08-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_auto_20200818_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='PhoneNo',
            field=models.BigIntegerField(max_length=15),
        ),
    ]
