# Generated by Django 3.0.9 on 2020-08-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_auto_20200818_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='PhoneNo',
            field=models.BigIntegerField(),
        ),
    ]
