# Generated by Django 3.0.9 on 2020-08-21 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_auto_20200819_2136'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
